#+title: How to improve performance

When doing some serious programming in BASH you'll sooner or later
encounter that BASH doesn't perform well when processing hundreds of
megabytes of text files. Here's some tricks I've learned that will
significanlty boost the performance of your BASH scripts.

* sed
You can significantly speed up things by executing all your sed
commands in the same process.

To illustrate; this is slow:
#+begin_src sh
echo foo | sed 's/foo/bar/p' | sed 's/bar/baz/p'
#+end_src

And this is fast:
#+begin_src sh
echo foo | sed -e 's/foo/bar/p' -e 's/bar/baz/p'
#+end_src
For bigger things, I'd recommend using a separate =file.sed= and call
it from your BASH script with =echo ${string} | sed -f file.sed=.

* grep
Often you'll find yourself grep-ing after a number of things. For
instance, if you're writing a log file analyser, you'll start off by
iterating over 20 interesting patterns in your log file, from which
you'd generate a report.

Although, codewise beautfully readable, this is painfully slow:
#+begin_src sh
for el in foo-error, bar-error-, baz-error;
   grep $el file.log
done
#+end_src

This is _much_ faster:
#+begin_src sh
egrep "foo-error|bar-error|baz-error" file.log
#+end_src
To give you an idea of _how_ much faster this is, I can tell you that
I had a log analyser searching for ~30 strings in ~800 megabytes of
data which spent half an hour on average. Using =egrep= instead of
=grep=, reduced the running time of the command from ~30 seconds to ~3
seconds.

* The power of a while read loop
Albeit this doesn't make your scripts faster, it's paramount to the
scalability of some programs. When handling a lot of data, you'll find
that for-each looping doesn't scale big enough (you'll get complaints
about resources/handles not big enough):

#+begin_src sh
for el in $(get_data); do
  do_something ${el}
done
#+end_src

Hence, if you get problems with this scaling, instead do a while-read
loop as this will never (in my experience) exhaust your system
resources:

#+begin_src sh
get_data | while read el; do
  do_something ${el}
done
#+end_src
