#+title: Resolving Deployment Issues on JBoss 7

** find-missing-jboss-module-dependencies
I've written a command especially for JBoss (tested on JBoss 7.x/EAP
6./ called [[https://github.com/skybert/moria/blob/master/src/java/find-missing-jboss-module-dependencies][find-missing-jboss-module-dependencies]] which will greatly
help you analyzing and resolving issues when deploying your artifacts
on JBoss.

Here, I have to WAR artifacts which failed to deploy. Running the
find-missing-jboss-module-dependencies quickly identifies the problem
and suggests a valid solution.

#+begin_src text
torstein@quanah ~$ find-missing-jboss-module-dependencies
from [Module "deployment.skybert-central-assetmanagement-webservice.war
  > Missing dependency:  net.skybert.amqp.connection.config.ConfiguredQpidConnectionFactoryCreator
  > JBoss module containing this dependency: Not found :-(
  > Maven artifact containing this dependency:
    >> skybert-app/skybert-amqp-connection-config/2.12.0.0-SNAPSHOT
from [Module "deployment.skybert-central-assignment-webservice.war
  > Missing dependency:  net.skybert.cs.eventing.publisher.EventingPublisher
  > JBoss module containing this dependency: Not found :-(
  > Maven artifact containing this dependency:
    >> skybert-app/skybert-webservices-eventing-publisher/2.12.0.0-SNAPSHOT
#+end_src

=find-missing-jboss-module-dependencies= will first see if the missing
dependency can be found in one of the JBoss modules. If it cannot
find the dependency there, it will go on looking in your local Maven
repository for the artifact you need to add to your POM.


** CXF
If your webapps use [[http://cxf.apache.org][CXF]], the easiest way to get them working is to
disable the =webservices= subsystem in JBoss.

#+begin_src nxml
<jboss-deployment-structure xmlns="urn:jboss:deployment-structure:1.2">
    <deployment>
        <exclude-subsystems>
            <subsystem name="webservices" />
        </exclude-subsystems>
    </deployment>
</jboss-deployment-structure>
#+end_src

See the [[https://cxf.apache.org/docs/application-server-specific-configuration-guide.html#ApplicationServerSpecificConfigurationGuide-JBossApplicationServer][CXF documentation]] for further details.
