#! /usr/bin/env/bash

# will make the mouse pointer invisible after two seconds of idleness
unclutter -idle 2 &

# setting up my two screens with xinerama and portrait mode on the
# external one.
xrandr --output VGA-1 --right-of LVDS-1 --auto --rotate left

# turn off CAPS LOCK, it creates more harm than good
setxkbmap -option ctrl:nocaps

# I also want some GNOME goodness on my fluxbox desktop
gnome-settings-daemon &
gnome-volume-manager &
gnome-power-manager &
gnome-display-properties &

# Brilliant clip board
/usr/lib/glipper/glipper -w &

# Get the right screensaver
killall -9 gnome-screensaver
xscreensaver &

# wallpaper
display -window root -backdrop ~/graphics/wallpaper &

# And at last, launch fluxbox
exec fluxbox -log ~/.fluxbox/log
