#+title: Why Vizrt isn't using Puppet for its SaaS platform

* Introduction
I wrote this as [[http://forum.vizrt.com/showthread.php?t=5948][a response to some Puppet question]] on the Vizrt forum
related to Puppet and Vizrt's fully automatic installation of
production ready clusters.

I keep it here in case it goes off the Vizrt forum and as a reference
to everyone who thinks my reluctance on using Puppet is down to
missing experience with the software.


* The Answer
[[http://forum.vizrt.com/showthread.php?t=5948][Posted on the Vizrt Forum]] 01-29-2013, 07:36 AM
  
#+begin_quote
Hi there,

the short answer is: all the Puppet related files in ece-scripts are
obsolete and not used anymore. If you want to use =ece-install= with
Puppet, then let Puppet generate the ece-install.conf files and then
call ece-install from within Puppet.

Some background for you in case you're curious why we're not using
Puppet: We started out developing the Vizrt Online SaaS platform using
Puppet. However, after 3-5 months, we ditched it as it slowed us down
more than anything. Before I proceed: This is not flame bait, it's
just an explanation for our choices. There were three issues with
Puppet and the way we've developed our SaaS solution:

1) We focus everything we do on getting installation of a new server
   as fast as possible and give it zero, 0, value. Setting up a new
   KVM or Amazon machine is now done in ~10 minutes. The only servers
   we care about is our source control system and the actual data on
   our DB and file servers. Hence, if we've got problems with a server
   in the rig, we just re-install it. That's the driving force:
   getting the installation of a new server as fast as possible and
   don't care as much about keeping the server around for a long time
   (this is were Puppet excels IMHO).

We times we _do_ change running systems, it's to make a new deployment
of the portal software (templates, Java, ECE version++). Here, we
build a new EAR and a DEB package with the configuration changes and
deploy these together with an publication resources using
ece-deploy [4].

2) We wanted the installation scripts to be completely independent on
   both the platform (virtual or physical) and change management
   framework (Puppet, Chef, Slack++). Hence, we implemented
   ece-install in pure BASH with as few ties to the OS as
   possible. You can read more about the design choices in the man
   pages [1] (man ece-install).

For this reason, we couldn't implement the installation itself in
Puppet. Hence, we had to pass flow control between Puppet and
ece-install and back again. This turned out to be a tough nut as
Puppet doesn't like this way of working. It likes to be in control of
everything and IMHO, doesn't have good ways of passing control (and
values) back and forth between itself and external scripts. It does
more a "fire off a call to a script and forget" approach, which didn't
serve us well enough. I'm sure it's possible to get it working (with
_did_ make it, just not satisfactory), but we didn't have the time for
this. After several months of battling with Puppet, we ditched it for
everything but user creation.

Since then, we've written spore [2], which does the user creation for
us, so then we've removed Puppet completely from all our servers. It
shaved off both the install size (don't need Ruby installed
everywhere) and installation time as a bonus.

3) We discovered anomalies that we couldn't explain (which seem to be
   bugs in Puppet): some of our configuration files (/etc/hosts is one
   example) would contain data inconsistent with what it should
   have. It seemed obvious that Puppet had gotten confused after we
   had added/removed/changed lines back and forth on the
   master. Eventually, we've got some servers with different conf
   files than they should have had.

I hope this gave answers to some of the whys I'm sure come to everyone
when they here we're neither using Puppet nor Chef - not even Slack,
but are just BASHing our way through everything. "Are they completely
mad?". No, we're not mad. Puppet is sure a great thing that serve many
people well. It just didn't for us, so we ventured down a different
road with BASH and DEB packages instead and we're happy with this :-)

Cheers,

-Torstein
#+end_quote

[1] [[https://github.com/vizrt/ece-scripts...tall-guide.org][https://github.com/vizrt/ece-scripts...tall-guide.org]]

[2] [[https://github.com/vizrt/spore][https://github.com/vizrt/spore]]

[4] [[https://github.com/vizrt/ece-scripts...ploy-guide.org][https://github.com/vizrt/ece-scripts...ploy-guide.org]]
