#+title: The Android apps I cannot live without

I recently had to switch back to using my old [[http://en.wikipedia.org/wiki/HTC_Desire][HTC Desire]]
from 2010. First of all, was love to finally have some physical
buttons again!

Since this is now an old phone, I was determined to only install the
apps I just couldn't live without. All the other "nice to have", like
the [[https://play.google.com/store/apps/details?id=vivino.web.app][Vivino]] wine app, had to go.

The apps I've found I cannot live without are:

* The ones I've downloaded
** Pocket (formerly known as "Read it later")
The [[http://getpocket.com/][Pocket]] app is my link collector and offline web article reader. It
also makes the articles a lot nicer to read by stripping out all the
fluff and choosing a nice font and colours for pleasant reading.

** Wunderlist
The [[https://www.wunderlist.com/][Wunderlist]] app is excellent for managing and sharing my TOOD lists
and my preferred platform on which to implement [[http://en.wikipedia.org/wiki/Getting_Things_Done][GTD]].

** Evernote
I use [[http://evernote.com][Evernote]] for ideas, articles and pictures from which I want to
build and develop into my own articles, presentations, blog posts,
tweets and the like.

The difference from Pocket, is that I first save everything
that *might* be interesting to Pocket and when I *know* it's
interesting, I add it to [[http://evernote.com][Evernote]].

And if you were in doubt, [[http://evernote.com][Evernote]] is great for note taking too ;-)

** Feedly
I love reading technical news feeds and [[https://play.google.com/store/apps/details?id=com.devhd.feedly][Feedly]] is the best app I've
found for doing so. It migrated my old Google Reader settings nicely
and I haven't missed the official RSS/Atom feed reader one bit.

** Twitter
As the web in general and social websites like Facebook in particular
get more and more bloated, I like [[http://twitter.com][Twitter]] more and more as the days
go by.

I find the official Twitter client to be superior to the client that
comes with HTC Desire, although the HTC client is wonderfully
uncluttered.

* The ones that came with the phone
** GMail
I use the standard [[https://play.google.com/store/apps/details?id=com.google.android.gm][Google GMail]] app all the time, and it's unthinkable
not to have it. Email is in my opinion the best invention of the
internet and GMail is the best Android app I've found to use it.

** Calendar
Just like the GMail app, I cannot live without the calendar, it's one
of the reasons why I get through my day :-)

** Google Talk
This phone is so old, there's no update in which the beautifully simple
[[https://play.google.com/store/apps/details?id=com.google.android.talk][Google Talk]] is transformed to a more bloated/feature rich/fancy
Google Hangout. Another benefit of running and old version of Android!

In any case, instant messaging using [[https://xmpp.org/xmpp-software/clients/][XMPP/Jabber]] is probably *the*
internet service I use most these days. Totally and utterly
indispensable on my mobile phone. I've moved the Google Talk icon so
that it's the easiest to reach for, before text messages or phone, on
my mobile phone.

** Android Music Player
I'm constantly listening to music and I like to carry a good
selection of music on my phone. One of the things I instantly loved
about Android, was that my OGG files, about 70% of my music
collection, played out of the box.

Of the differnet music players on Android, I really like the stock
Android player that comes with the phone.

** Clock
Totally indispensable. Alarm, countdown timer, time. Differnt
timezones.

* Honourable mention

** Opera Mini
The [[http://opera.com/mobile][Opera Mini browser]] is an incredibly fast excellent alternative on
Android. Since this phone is such an old one, I use Opera mini to make
the browser experience as swift as possible.

This app isn't an app I cannot live without, but a "nice to have" and
a "must have" on an old phone :-)

* That's it!
That's it. That's all the apps I use on my now four year old phone
and the top apps I will install on my new Android phone - whenever I
get it back from repairs.

What do you think? What are your favourite apps?

